### ISSUE TITLE
Add function to the "I'm feeling lucky" button

### ISSUE THREAD

**Issue by shafinshaikh** [jayantghadge/searchify#1]
Add some functionality like redirecting to random quote or trivia after clicking on I'm feeling lucky button. And if the user has entered phrases for search and then clicks on "I'm Feeling Lucky" button then the search should bypass the results page and take the user directly to the first website amongst the search results

**Comment by jayantghadge** [comment]
> Add some functionality like redirecting to random quote or trivia after clicking on I'm feeling lucky button. And if the user has entered phrases for search and then clicks on "I'm Feeling Lucky" button then the search should bypass the results page and take the user directly to the first website amongst the search results

Thank you for creating the issue regarding the "I'm Feeling Lucky" button functionality. I've reviewed the request, and I appreciate your suggestion!
